version: "3"

services:
  server:
    build: ./server
    volumes:
      - ./server:/app/
      - /app/node_modules

  client:
    build: ./client
    volumes:
      - ./client:/app/
      - /app/node_modules

volumes:
  server:
