version: "3"

services:
  server:
    build: ./server
    depends_on:
      - db
    volumes:
      - ./server:/app/
      - /app/node_modules

  client:
    build: ./client
    volumes:
      - ./client:/app/
      - /app/node_modules

  db:
    container_name: contento_db
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  server:
  client:
