version: "3"

services:
  server:
    container_name: contento_server
    ports:
      - "7077:7077"
    env_file:
      - ./server/.env

  client:
    container_name: contento_client
    ports:
      - "3033:3033"
    depends_on:
      - server
