apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: contento-server
    labels:
        app: contento-266211
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: contento-266211
        spec:
            containers:
                - name: contento-server
                  image: docker.io/marvinkome/contento-server
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 7077
                  envFrom:
                      - secretRef:
                            name: contento-server-prod-secret
