name: Client CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "client/**"
      - ".github/workflows/client*"
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-18.04
    container:
      image: cypress/base:11.13.0

    steps:
      - uses: actions/checkout@v2
      - name: Copy env
        run: cp ./client/.env.example ./client/.env
      - name: Cypress test
        uses: cypress-io/github-action@v1
        with:
          working-directory: client
          config-file: cypress.ci.json
          start: yarn start
          wait-on: "http://localhost:3033"

  cd:
    runs-on: ubuntu-18.04
    if: github.event.push.ref == 'refs/heads/master' || github.ref == 'refs/heads/master'
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -f ./client/Dockerfile.prod -t contento_client ./client

      - name: Tags
        run: |
          docker tag contento_client ${{ secrets.DOCKER_USER }}/contento_client:${{ github.sha }}
          docker tag contento_client ${{ secrets.DOCKER_USER }}/contento_client:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/contento_client:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/contento_client:latest
