name: Client CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "client/**"
      - ".github/workflows/client*"
  pull_request:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: contento-cluster
  GKE_ZONE: europe-west1-b
  DEPLOYMENT_NAME: contento-client-dep
  IMAGE: contento-client

jobs:
  ci:
    runs-on: ubuntu-18.04
    container:
      image: cypress/base:11.13.0

    steps:
      - uses: actions/checkout@v2
      - name: Copy env
        run: cp ./client/.env.example ./client/.env
      - name: Cypress test
        uses: cypress-io/github-action@v1
        with:
          working-directory: client
          config-file: cypress.ci.json
          start: yarn start
          wait-on: "http://localhost:3033"

  cd:
    runs-on: ubuntu-18.04
    if: github.event.push.ref == 'refs/heads/master' || github.ref == 'refs/heads/master'
    needs: ci

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -f ./client/Dockerfile.prod -t contento-client ./client

      - name: Tags
        run: |
          docker tag contento-client ${{ secrets.DOCKER_USER }}/contento-client:${{ github.sha }}
          docker tag contento-client ${{ secrets.DOCKER_USER }}/contento-client:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/contento-client:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/contento-client:latest

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Create Kustomize file
        run: |-
          cat <<EOF >./kustomization.yaml
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - ./k8/contento-client.yml
          EOF

      - name: Deploy
        run: |-
          ./kustomize edit set image docker.io/IMAGE:TAG=docker.io/marvinkome/$IMAGE:${{ github.sha }}
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
