name: Client CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-18.04
    container:
      image: node:11.15.0

    steps:
      - name: install os deps
        run: apt-get install \
          libgtk2.0-0 \
          libgtk-3-0 \
          libnotify-dev \
          libgconf-2-4 \
          libnss3 \
          libxss1 \
          libasound2 \
          libxtst6 \
          xauth \
          xvfb
      - uses: actions/checkout@v2
      - name: Cypress test
        uses: cypress-io/github-action@v1
        with:
          working-directory: client
  cd:
    runs-on: ubuntu-18.04
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t contento_client ./client

      - name: Tags
        run: |
          docker tag contento_client ${{ secrets.DOCKER_USER }}/contento_client:${{ github.sha }}
          docker tag contento_client ${{ secrets.DOCKER_USER }}/contento_client:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/contento_client:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/contento_client:latest
