name: Client CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:11.15.0

    steps:
      - uses: actions/checkout@v2
      - name: install and test
        run: |
          cd client
          yarn install --frozen-lockfile
          yarn ci:test
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t contento_client ./client

      - name: Tags
        run: |
          docker tag contento_client ${{ secrets.DOCKER_USER }}/contento_client:${{ github.sha }}
          docker tag contento_client ${{ secrets.DOCKER_USER }}/contento_client:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/contento_client:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/contento_client:latest
