name: Server CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:11.15.0

    steps:
      - uses: actions/checkout@v2
      - name: install and test
        run: |
          cd server
          yarn install --frozen-lockfile
          yarn test
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t contento_server ./server

      - name: Tags
        run: |
          docker tag contento_server ${{ secrets.DOCKER_USER }}/contento_server:${{ github.sha }}
          docker tag contento_server ${{ secrets.DOCKER_USER }}/contento_server:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/contento_server:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/contento_server:latest
