name: Server CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
      - ".github/workflows/server*"
  pull_request:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: contento-cluster
  GKE_ZONE: europe-west1-b
  DEPLOYMENT_NAME: contento-server-dep
  IMAGE: contento-server

jobs:
  ci:
    runs-on: ubuntu-18.04
    container:
      image: node:12.0.0

    steps:
      - uses: actions/checkout@v2
      - name: install and test
        run: |
          cd server
          yarn install --frozen-lockfile
          yarn test
  cd:
    runs-on: ubuntu-18.04
    if: github.event.push.ref == 'refs/heads/master' || github.ref == 'refs/heads/master'
    needs: ci

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -f ./server/Dockerfile.prod -t contento-server ./server

      - name: Tags
        run: |
          docker tag contento-server ${{ secrets.DOCKER_USER }}/contento-server:${{ github.sha }}
          docker tag contento-server ${{ secrets.DOCKER_USER }}/contento-server:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/contento-server:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/contento-server:latest

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          ./kustomize edit set image docker.io/IMAGE:TAG=docker.io/marvinkome/$IMAGE:${{ github.sha }}
          ./kustomize build ./k8 | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
